//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.Problems = new HashSet<Problem>();
        }
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Name is required")]
        [StringLength(20)]
        [RegularExpression(@"^[a-zA-Z0-9\s]*$", ErrorMessage ="Contains letters, digits only")]
        [Display(Name ="Property's Name")]
        
        public string Name { get; set; }

        public string Description { get; set; }
        [Required(ErrorMessage = "Price is required")]
        [Range(1,100000)]
        public int Price { get; set; }
        [Required(ErrorMessage = "Acquiring Date is required")]
        [Display(Name = "Acquiring Date")]

        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Problem> Problems { get; set; }
    }
}
